import Head from 'next/head';

export const MetaTags = () => {
    return (
        <Head>
            <title>Direto ao Ponto | Ebook</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="viewport" content="initial-scale=1, width=device-width" />
            <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
        </Head>
    )
}