import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { PageHeader } from '../components/PageHeader'
import { ProductItems } from '../components/ProductItems'
import {EbookContents} from '../components/EbookContents'
import { Footer } from '../components/Footer'



export default function Home() {
  return (

    <> 

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"/>
      </Head>

      <PageHeader/>
      <hr></hr>
      <EbookContents /> 
      <hr></hr>
      <ProductItems />
      <hr></hr>
      <Footer /> 
      
    
    </>
      
  )
}
